%% Problem 2

% Each new term in the Fibonacci sequence is generated by adding the 
% previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% 
% By considering the terms in the Fibonacci sequence whose values do not 
% exceed four million, find the sum of the even-valued terms.

%% Implementation
% while loop to set limit on Fibonacci values


n = 1;
% Initial fibonacci sequence
Fibvec = [1 2];


index = 2;
while Fibvec(index) < 4e6 

Fibvec(index+1) = Fibvec(index)+Fibvec(index-1);
index = index + 1;

end


%% Find all even numbers and sum them

% interesting pattern relation betweem even fibonacci numbers 
% occurs at a distance of 2 between every even fib number
evens = double(mod(Fibvec,2) == 0);

newFibs = Fibvec.*evens;

newFibsum = sum(newFibs)




