%% Problem 12 

% The sequence of triangle numbers is generated by adding the 
% natural numbers. So the 7th triangle number 
% would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
% 
% 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
% 
% Let us list the factors of the first seven triangle numbers:
% 
%  1: 1
%  3: 1,3
%  6: 1,2,3,6
% 10: 1,2,5,10
% 15: 1,3,5,15
% 21: 1,3,7,21
% 28: 1,2,4,7,14,28
% We can see that 28 is the first triangle number to have over 5 divisors.
% 
% What is the value of the first triangle number to have over 500 divisors?

%% Implementation 

myTriNums = 1e4:1e5; 
myTriNums = cumsum(myTriNums);

% Find Number of factors within range and match numbers with condition of
% having over 500 divisors(factors). 

% Consider divisor function for triangular numbers
% 
% Nf = 8e8
% Ni = Nf-1e8
Nf = 76576501; % +1
Ni = Nf-2;
Nvec = []; % vector to store number of factors for each number
Facs = []; % vector to store local factors of number
               
tic;
for i = Ni:Nf 
    Dvec = 1:i;  
    if sum(mod(i,Dvec) == 0) > 500 % check divisible numbers
        Facs = [Facs i]; % store factors
    end
end 

Facs

elapsedTime = toc
